# Generated by Django 4.1.2 on 2022-10-24 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_caregory_detil_category_remove_caregory_detil_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregory_detil',
            name='category',
        ),
        migrations.AddField(
            model_name='caregory_detil',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.category'),
        ),
    ]
