# Generated by Django 4.1.2 on 2022-10-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_Detail',
        ),
        migrations.DeleteModel(
            name='Caregory_detil',
        ),
    ]
