# Generated by Django 4.1.2 on 2022-10-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
        migrations.RemoveField(
            model_name='category',
            name='text',
        ),
    ]
