# Generated by Django 4.1.2 on 2022-10-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_delete_new_remove_category_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_detail',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='videos.category_detail'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category_detail',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
