# Generated by Django 4.1.2 on 2022-10-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_category_detail_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_detail',
            name='created',
        ),
    ]
