# Generated by Django 4.1.2 on 2022-10-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_remove_category_detail_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
