# Generated by Django 4.1.2 on 2022-10-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_category_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_detail',
            old_name='title',
            new_name='detail',
        ),
    ]
