# Generated by Django 4.1.2 on 2022-10-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_rename_title_category_detail_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(null=True, to='videos.category_detail'),
        ),
    ]
