# Generated by Django 4.1.2 on 2022-10-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_alter_video_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
