# Generated by Django 4.1.2 on 2022-10-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_remove_category_category_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='videos.category_detail'),
        ),
    ]
