# Generated by Django 4.1.2 on 2022-10-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0025_category_detail_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
