# Generated by Django 4.1.2 on 2022-10-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='videos.category_detail')),
            ],
        ),
    ]
