# Generated by Django 4.1.2 on 2022-10-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0027_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_detail',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
