# Generated by Django 4.1.2 on 2022-10-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0032_rename_title_category_detail_ti_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_detail',
            old_name='ti',
            new_name='title',
        ),
    ]
