# Generated by Django 4.1.2 on 2022-10-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0033_rename_ti_category_detail_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_detail',
            old_name='title',
            new_name='tit',
        ),
    ]
