# Generated by Django 4.1.2 on 2022-10-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0034_rename_title_category_detail_tit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_detail',
            old_name='tit',
            new_name='title',
        ),
    ]
